---
- name: Add MySQL repository
  copy:
    dest: /etc/yum.repos.d/mysql8.repo
    content: |
      [mysql80-community]
      name=MySQL 8.0 Community Server
      baseurl=http://repo.mysql.com/yum/mysql-8.0-community/el/7/$basearch/
      enabled=1
      gpgcheck=0

- name: Install MySQL8 
  yum: name={{ item }} state=present
  loop: [ 'mysql-community-client', 'mysql-community-server', 'python-PyMySQL' ]

- name: Enable and start MySQL
  systemd:
    name: mysqld
    enabled: yes
    state: started

# ==========================================
# Comment this after mysql install (for future use)

#- name: Get temp MySQL root password
#  shell: |
#    grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | tail -1 | awk -F ' ' '{print $(NF)}'
#  register: temp_root_password        
    
#- name: Print temp MySQL root password
#  debug:
#    msg: "Temp MySQL root password is: {{ temp_root_password.stdout }}"

#- name: Print new MySQL root password ( just for debugging )
#  debug:
#    msg: "New MySQL root password will be: {{ mysql_root_password }}"

#- name: Change root password
#  shell: |
#    mysql --user root --password="{{ temp_root_password.stdout }}" --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"    

# ===========================================

- name: Create database for Wordpress  
  mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_db }}"
    state: present

- name: Create user for wp database
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: 'wp.*:ALL,GRANT'
    host: "{{ remote_host }}"
    state: present

- name: Flush privileges
  shell: mysql --user root --password={{ mysql_root_password }} --execute "FLUSH PRIVILEGES;"    